# docker-compose.yml
version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.4
    container_name: gradeqslot_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gradeqslot
      MYSQL_ROOT_PASSWORD: gradeqslot1234
      MYSQL_USER: gradeqslot
      MYSQL_PASSWORD: gradeqslot1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - gradeqslot_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gradeqslot_backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:8000"
    environment:
     - APP_ENV=local
     - APP_DEBUG=true
     - APP_URL=http://localhost:8000
    depends_on:
      - mysql
    networks:
      - gradeqslot_network

  # Vuetify Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gradeqslot_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    depends_on:
      - backend
    networks:
      - gradeqslot_network

  # Nginx (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: gradeqslot_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/public:/var/www/html/public
    depends_on:
      - backend
      - frontend
    networks:
      - gradeqslot_network

volumes:
  mysql_data:

networks:
  gradeqslot_network:
    driver: bridge
